const router = require('express').Router();
const auth = require('../middlewares/auth');
const c = require('../controllers/ventasCreditoController');
router.use(auth);
router.get('/', c.getAll);
router.get('/cartera', c.resumenCartera);
router.get('/:id', c.getOne);
router.post('/', c.create);
router.post('/:id/abonos', c.agregarAbono);
router.put('/:id', c.update);
router.delete('/:id', c.remove);
module.exports = router;
